export const POKEMON_LIST_REQUEST = 'POKEMON_LIST_REQUEST';
export const POKEMON_LIST_SUCCESS = 'POKEMON_LIST_SUCCESS';
export const POKEMON_LIST_FAIL = 'POKEMON_LIST_FAIL';

export const POKEMON_DETAIL_REQUEST = 'POKEMON_DETAIL_REQUEST';
export const POKEMON_DETAIL_SUCCESS = 'POKEMON_DETAIL_SUCCESS';
export const POKEMON_DETAIL_FAIL = 'POKEMON_DETAIL_FAIL';

export const POKEMON_ITEM_REQUEST = 'POKEMON_ITEM_REQUEST';
export const POKEMON_ITEM_SUCCESS = 'POKEMON_ITEM_SUCCESS';
export const POKEMON_ITEM_FAIL = 'POKEMON_ITEM_FAIL';
